### ISSUE TITLE
sync with mdnotes-Addon Output

### ISSUE THREAD

**Issue by benpla** [daeh/zotero-obsidian-citations#1]
I had this post also on [obsidian-Forum](https://forum.obsidian.md/t/new-plugin-citations-with-zotero/9793/318?u=bepl) as Reply:

I find your addon SUPER, even if it has not yet led to the goal or success with me.

I export Zotero items that I want to work with in Obsidian with the Zotero addon "mdnotes".
This creates Markdown files with the title 
"@CITEKEY.md" (example: "@Akal_ea_2018_DistributedSensing.md").
   

These are located in the Obsidian Vault in a folder. The files also contain the additional Zotero link with the Zotero ID as the metadata field:
```
...
- title:: A Distributed Sensing Approach for Single Platform Image-Based Localization
- local:: [local zotero](zotero://select/items/1_4AYCPGBV)
- cloud:: http://zotero.org/users/4847583/items/4AYCPGBV
...
```
Example file: [@Akal_ea_2018_DistributedSensing.md](https://1drv.ms/u/s!AolAK05zrTBRg5sPo_bgoyyK9h5pmg?e=59VBAf)

The corresponding Zotero items should now get a tag "ObsCite".
In my case, there is NO exported JSON file of all Zotero items. Your addon aborts the sync with the error message "BBT JSON Library not found". 
What is the purpose of the BBT JSON Library? Surely the information is directly accessible to the addon in Zotero?
My Zotero contains about 80000 entries. If I would set an auto-export, every time I make a change in Zotero, the whole database would be exported. 

In my opinion, this file is not necessary:
  - Search Obsidian folder
  - each file starting with "@" is a citekey probably present in Zotero
  - Search this citekey in the Zotero database
  - if found, then assign tag "ObsCite
  - if not found (e.g. because deleted in Zotero in the meantime but still present in Obsidian), then write to a "missing entry" list
  - Write the list with the missing entries:
      - as a Zotero note or 
      - write it as a Markdown file into the specified folder with the citekeys 
      - Suggested name: "zotero-obsidian-citations missing-entries.md".

Is there a reason for needing the BBT JSON library that I'm just not seeing?

**Comment by daeh** [comment]
Thanks for posting this as an issue. 

A work around here is to allow the user to specify a regex to pull the zotero ID from the metadata, in your case, `- local::`. I can definitely implement that. A question for you, I'm accustomed to MD metadata taking for form of
```md
---
key1: val1
key2: val2
---
```

What metadata specification takes the format that yours uses?
```
...
- key1:: val1
...
```

**Comment by daeh** [comment]
@benpla See if v0.0.2 works for you. I included the regex that I think you'll need in the readme

**Comment by daeh** [comment]
closed via 7ac2d4aeafc9807d1f0cbb4c2619c9a3d8cceebd, but please reopen if this doesn't accommodate your use case

**Comment by benpla** [comment]
Good Morning (from Germany),
bitte entschuldigen Sie meine späte Meldung, ich sitze erst jetzt wieder vor einem Computer.
Zuerst: TOLLE ARBEIT. Vielen Dank, @daeh !
Ich habe es getestet, es funktioniert hervorragend!

Ich habe noch eine weitere Bitte. Dafür öffne ich einen neuen Issue

**Comment by daeh** [comment]
Great. Glad to hear it.

**Comment by daeh** [comment]
hi @benpla  - I made an update that means you'll no longer need to use an auto-updating BBT JSON file. Would you be up for trying the 0.0.11 pre-release and letting me know if works for you? https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11pre.xpi

**Comment by daeh** [comment]
Hi @benpla - v0.0.11 removes the need for the BBT JSON library export. (Please let me know if it breaks anything!)
