### ISSUE TITLE
Bug with the last update!!!

### ISSUE THREAD

**Issue by WMAM** [daeh/zotero-obsidian-citations#10]
Zotero auto-updated the add-on, and after rebooting:
1. I can't enter into the Tools>Add-ons (no action!)
2. Looks like the BBT plugin is not working anymore
3. Your plugin does not update new notes from Obsidian

Zotero has no update, so it should not be a bug from their side.

EDIT: As the command menu "Add-ons" does not work, I can't even uninstall it.

**Comment by daeh** [comment]
Hi @WMAM - That's extremely bizarre (I can't imagine what could prevent you from being able to open the Add-ons menu). Can you let me know what version of Zotero you're running so that I can try to reproduce it? Thanks for letting me know. 

To disable the addon, you can run this code in the Javascript console (`Tools -> Developer -> Run JavaScript`):

be sure to check the "Run as async" box.
```js
Components.utils.import("resource://gre/modules/AddonManager.jsm");

var deferred = Zotero.Promise.defer();
function onHaveInstalledAddons(installed) {
	var addons = [];
	for (let addon of installed) {
		if (addon.id === 'daeda@mit.edu') {
			addon.userDisabled = true;
			addons.push(addon);
		}
	}
	deferred.resolve(addons);
}

AddonManager.getAllAddons(onHaveInstalledAddons);
return deferred.promise;
```
Then restart Zotero and you should be able to open the Add-on pane. If you want, you can install the previous version (0.0.10) and set it to not auto-update while I track down the source of this bug.

**Comment by WMAM** [comment]
Hi!
Thank you for your answer! I am running Windows 11 & Zotero 5.0.97-beta.63+035aac30f

I did not succeed to open the addon menu after running that code 2 or 3 times.

Restarting Zotero appears this message SliceObj Error:1

**Comment by daeh** [comment]
@WMAM can you post the output of that code snippet here?

**Comment by WMAM** [comment]
I don't know if this can help you... On Github v.0.11 says that the JSON library is not necessary anymore, but the ObsidianCitationPreference is still giving that option:
![imagen](https://user-images.githubusercontent.com/31582800/149974220-3cbefb58-e7e3-4816-bbdc-4dcf33f06029.png)

**Comment by WMAM** [comment]
[
    "0": {
        "__AddonInternal__": undefined
        "seen": true
        "hasEmbeddedWebExtension": false
        "markAsSeen": markAsSeen() {...}
        "type": "extension"
        "isWebExtension": false
        "isAPIExtension": false
        "temporarilyInstalled": false
        "aboutURL": null
        "optionsURL": null
        "optionsType": null
        "optionsBrowserStyle": undefined
        "iconURL": null
        "icon64URL": null
        "icons": {}
        "screenshots": null
        "applyBackgroundUpdates": 1
        "syncGUID": "{4f72e6f7-63e6-41d1-a5ff-dac82e7c43fb}"
        "install": null
        "pendingUpgrade": {
            "__AddonInternal__": undefined
            "seen": true
            "hasEmbeddedWebExtension": false
            "markAsSeen": markAsSeen() {...}
            "type": "extension"
            "isWebExtension": false
            "isAPIExtension": false
            "temporarilyInstalled": false
            "aboutURL": null
            "optionsURL": null
            "optionsType": null
            "optionsBrowserStyle": undefined
            "iconURL": null
            "icon64URL": null
            "icons": {}
            "screenshots": null
            "applyBackgroundUpdates": 1
            "syncGUID": "{7b6fd96d-de4c-4ee4-b456-9c6e58ae3e03}"
            "install": {
                "__AddonInstallInternal__": undefined
                "type": "extension"
                "iconURL": undefined
                "existingAddon": <<Reference to parent object ROOT->0 >>
                "addon": <<Reference to parent object ROOT->0->pendingUpgrade >>
                "sourceURI": [object XPCWrappedNative_NoHelper] {
                    "spec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "prePath": "https://github.com"
                    "scheme": "https"
                    "userPass": ""
                    "username": ""
                    "password": ""
                    "hostPort": "github.com"
                    "host": "github.com"
                    "port": -1
                    "pathQueryRef": "/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "equals": function equals() { [native code] }
                    "schemeIs": function schemeIs() { [native code] }
                    "clone": function clone() { [native code] }
                    "resolve": function resolve() { [native code] }
                    "asciiSpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "asciiHostPort": "github.com"
                    "asciiHost": "github.com"
                    "ref": ""
                    "equalsExceptRef": function equalsExceptRef() { [native code] }
                    "cloneIgnoringRef": function cloneIgnoringRef() { [native code] }
                    "cloneWithNewRef": function cloneWithNewRef() { [native code] }
                    "specIgnoringRef": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "hasRef": false
                    "filePath": "/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "query": ""
                    "displayHost": "github.com"
                    "displayHostPort": "github.com"
                    "displaySpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                    "displayPrePath": "https://github.com"
                    "mutate": function mutate() { [native code] }
                    "QueryInterface": function QueryInterface() { [native code] }
                }
                "promptHandler": undefined
                "install": install() {...}
                "cancel": cancel() {...}
                "addListener": addListener(listener) {...}
                "removeListener": removeListener(listener) {...}
                "name": "ZoteroObsidianCitations"
                "version": "0.0.11"
                "icons": {}
                "releaseNotesURI": null
                "file": [object XPCWrappedNative_NoHelper] {
                    "QueryInterface": function QueryInterface() { [native code] }
                    "append": function append() { [native code] }
                    "normalize": function normalize() { [native code] }
                    "create": function create() { [native code] }
                    "leafName": "tmp-mcs.xpi"
                    "copyTo": function copyTo() { [native code] }
                    "copyToFollowingLinks": function copyToFollowingLinks() { [native code] }
                    "moveTo": function moveTo() { [native code] }
                    "renameTo": function renameTo() { [native code] }
                    "remove": function remove() { [native code] }
                    "permissions": <<Access Denied>>
                    "permissionsOfLink": <<Access Denied>>
                    "lastModifiedTime": <<Access Denied>>
                    "lastModifiedTimeOfLink": <<Access Denied>>
                    "fileSize": <<Access Denied>>
                    "fileSizeOfLink": <<Access Denied>>
                    "target": "C:\\Users\\wargu\\AppData\\Local\\Temp\\tmp-mcs.xpi"
                    "path": "C:\\Users\\wargu\\AppData\\Local\\Temp\\tmp-mcs.xpi"
                    "exists": function exists() { [native code] }
                    "isWritable": function isWritable() { [native code] }
                    "isReadable": function isReadable() { [native code] }
                    "isExecutable": function isExecutable() { [native code] }
                    "isHidden": function isHidden() { [native code] }
                    "isDirectory": function isDirectory() { [native code] }
                    "isFile": function isFile() { [native code] }
                    "isSymlink": function isSymlink() { [native code] }
                    "isSpecial": function isSpecial() { [native code] }
                    "createUnique": function createUnique() { [native code] }
                    "clone": function clone() { [native code] }
                    "equals": function equals() { [native code] }
                    "contains": function contains() { [native code] }
                    "parent": [object XPCWrappedNative_NoHelper] {
                        "QueryInterface": function QueryInterface() { [native code] }
                        "append": function append() { [native code] }
                        "normalize": function normalize() { [native code] }
                        "create": function create() { [native code] }
                        "leafName": "Temp"
                        "copyTo": function copyTo() { [native code] }
                        "copyToFollowingLinks": function copyToFollowingLinks() { [native code] }
                        "moveTo": function moveTo() { [native code] }
                        "renameTo": function renameTo() { [native code] }
                        "remove": function remove() { [native code] }
                        "permissions": 438
                        "permissionsOfLink": 438
                        "lastModifiedTime": 1642521716964
                        "lastModifiedTimeOfLink": 1642521716964
                        "fileSize": 106496
                        "fileSizeOfLink": 106496
                        "target": "C:\\Users\\wargu\\AppData\\Local\\Temp"
                        "path": "C:\\Users\\wargu\\AppData\\Local\\Temp"
                        "exists": function exists() { [native code] }
                        "isWritable": function isWritable() { [native code] }
                        "isReadable": function isReadable() { [native code] }
                        "isExecutable": function isExecutable() { [native code] }
                        "isHidden": function isHidden() { [native code] }
                        "isDirectory": function isDirectory() { [native code] }
                        "isFile": function isFile() { [native code] }
                        "isSymlink": function isSymlink() { [native code] }
                        "isSpecial": function isSpecial() { [native code] }
                        "createUnique": function createUnique() { [native code] }
                        "clone": function clone() { [native code] }
                        "equals": function equals() { [native code] }
                        "contains": function contains() { [native code] }
                        "parent": [object XPCWrappedNative_NoHelper] <<Maximum depth reached>>
                        "directoryEntries": [object XPCWrappedNative_NoHelper] <<Maximum depth reached>>
                        "initWithPath": function initWithPath() { [native code] }
                        "initWithFile": function initWithFile() { [native code] }
                        "followLinks": false
                        "diskSpaceAvailable": 172638588928
                        "appendRelativePath": function appendRelativePath() { [native code] }
                        "persistentDescriptor": "C:\\Users\\wargu\\AppData\\Local\\Temp"
                        "reveal": function reveal() { [native code] }
                        "launch": function launch() { [native code] }
                        "getRelativeDescriptor": function getRelativeDescriptor() { [native code] }
                        "setRelativeDescriptor": function setRelativeDescriptor() { [native code] }
                        "getRelativePath": function getRelativePath() { [native code] }
                        "setRelativePath": function setRelativePath() { [native code] }
                        "NORMAL_FILE_TYPE": 0
                        "DIRECTORY_TYPE": 1
                        "OS_READAHEAD": 1073741824
                        "DELETE_ON_CLOSE": 2147483648
                    }
                    "directoryEntries": <<Access Denied>>
                    "initWithPath": function initWithPath() { [native code] }
                    "initWithFile": function initWithFile() { [native code] }
                    "followLinks": false
                    "diskSpaceAvailable": 0
                    "appendRelativePath": function appendRelativePath() { [native code] }
                    "persistentDescriptor": "C:\\Users\\wargu\\AppData\\Local\\Temp\\tmp-mcs.xpi"
                    "reveal": function reveal() { [native code] }
                    "launch": function launch() { [native code] }
                    "getRelativeDescriptor": function getRelativeDescriptor() { [native code] }
                    "setRelativeDescriptor": function setRelativeDescriptor() { [native code] }
                    "getRelativePath": function getRelativePath() { [native code] }
                    "setRelativePath": function setRelativePath() { [native code] }
                    "NORMAL_FILE_TYPE": 0
                    "DIRECTORY_TYPE": 1
                    "OS_READAHEAD": 1073741824
                    "DELETE_ON_CLOSE": 2147483648
                }
                "state": 10
                "error": 0
                "progress": 17329
                "maxProgress": 17329
            }
            "pendingUpgrade": null
            "scope": 1
            "pendingOperations": 8
            "operationsRequiringRestart": 9
            "isDebuggable": false
            "permissions": 0
            "isActive": false
            "startupPromise": null
            "updateBlocklistState": updateBlocklistState(applySoftBlock = true) {...}
            "userDisabled": false
            "softDisabled": false
            "hidden": false
            "isSystem": false
            "isSyncable": true
            "userPermissions": null
            "isCompatibleWith": isCompatibleWith(aAppVersion, aPlatformVersion) {...}
            "uninstall": uninstall(alwaysAllowUndo) {...}
            "cancelUninstall": cancelUninstall() {...}
            "findUpdates": findUpdates(aListener, aReason, aAppVersion, aPlatformVersion) {...}
            "cancelUpdate": cancelUpdate() {...}
            "hasResource": hasResource(aPath) {...}
            "reload": reload() {...}
            "getResourceURI": getResourceURI(aPath) {...}
            "id": "daeda@mit.edu"
            "version": "0.0.11"
            "isCompatible": true
            "isPlatformCompatible": true
            "providesUpdatesSecurely": true
            "blocklistState": 0
            "blocklistURL": null
            "appDisabled": false
            "skinnable": false
            "size": 94098
            "foreignInstall": false
            "strictCompatibility": false
            "updateURL": "https://raw.githubusercontent.com/daeh/zotero-obsidian-citations/main/update.rdf"
            "dependencies": []
            "getDataDirectory": getDataDirectory(callback) {...}
            "multiprocessCompatible": false
            "signedState": 0
            "mpcOptedOut": false
            "isCorrectlySigned": false
            "fullDescription": null
            "developerComments": null
            "supportURL": null
            "contributionURL": null
            "averageRating": null
            "reviewCount": null
            "reviewURL": null
            "weeklyDownloads": null
            "installDate": "2022-01-12T07:20:11.717Z"
            "updateDate": "2022-01-18T05:50:17.616Z"
            "sourceURI": [object XPCWrappedNative_NoHelper] {
                "spec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "prePath": "https://github.com"
                "scheme": "https"
                "userPass": ""
                "username": ""
                "password": ""
                "hostPort": "github.com"
                "host": "github.com"
                "port": -1
                "pathQueryRef": "/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "equals": function equals() { [native code] }
                "schemeIs": function schemeIs() { [native code] }
                "clone": function clone() { [native code] }
                "resolve": function resolve() { [native code] }
                "asciiSpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "asciiHostPort": "github.com"
                "asciiHost": "github.com"
                "ref": ""
                "equalsExceptRef": function equalsExceptRef() { [native code] }
                "cloneIgnoringRef": function cloneIgnoringRef() { [native code] }
                "cloneWithNewRef": function cloneWithNewRef() { [native code] }
                "specIgnoringRef": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "hasRef": false
                "filePath": "/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "query": ""
                "displayHost": "github.com"
                "displayHostPort": "github.com"
                "displaySpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.11/zotero-obsidian-citations-0.0.11.xpi"
                "displayPrePath": "https://github.com"
                "mutate": function mutate() { [native code] }
                "QueryInterface": function QueryInterface() { [native code] }
            }
            "releaseNotesURI": null
            "name": "ZoteroObsidianCitations"
            "description": "Add a tag to Zotero items that have a external note."
            "creator": {
                "name": "Dae Houlihan"
                "url": undefined
                "toString": toString() {...}
            }
            "homepageURL": "https://github.com/daeh/zotero-obsidian-citations"
            "developers": undefined
            "translators": undefined
            "contributors": undefined
        }
        "scope": 1
        "pendingOperations": 18
        "operationsRequiringRestart": 6
        "isDebuggable": false
        "permissions": 11
        "isActive": true
        "startupPromise": null
        "updateBlocklistState": updateBlocklistState(applySoftBlock = true) {...}
        "userDisabled": true
        "softDisabled": false
        "hidden": false
        "isSystem": false
        "isSyncable": true
        "userPermissions": null
        "isCompatibleWith": isCompatibleWith(aAppVersion, aPlatformVersion) {...}
        "uninstall": uninstall(alwaysAllowUndo) {...}
        "cancelUninstall": cancelUninstall() {...}
        "findUpdates": findUpdates(aListener, aReason, aAppVersion, aPlatformVersion) {...}
        "cancelUpdate": cancelUpdate() {...}
        "hasResource": hasResource(aPath) {...}
        "reload": reload() {...}
        "getResourceURI": getResourceURI(aPath) {...}
        "id": "daeda@mit.edu"
        "version": "0.0.10"
        "isCompatible": true
        "isPlatformCompatible": true
        "providesUpdatesSecurely": true
        "blocklistState": 0
        "blocklistURL": null
        "appDisabled": false
        "skinnable": false
        "size": 92882
        "foreignInstall": false
        "strictCompatibility": false
        "updateURL": "https://raw.githubusercontent.com/daeh/zotero-obsidian-citations/main/update.rdf"
        "dependencies": []
        "getDataDirectory": getDataDirectory(callback) {...}
        "multiprocessCompatible": false
        "signedState": 0
        "mpcOptedOut": false
        "isCorrectlySigned": false
        "fullDescription": null
        "developerComments": null
        "supportURL": null
        "contributionURL": null
        "averageRating": null
        "reviewCount": null
        "reviewURL": null
        "weeklyDownloads": null
        "installDate": "2022-01-12T07:20:11.717Z"
        "updateDate": "2022-01-16T02:41:32.585Z"
        "sourceURI": [object XPCWrappedNative_NoHelper] {
            "spec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "prePath": "https://github.com"
            "scheme": "https"
            "userPass": ""
            "username": ""
            "password": ""
            "hostPort": "github.com"
            "host": "github.com"
            "port": -1
            "pathQueryRef": "/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "equals": function equals() { [native code] }
            "schemeIs": function schemeIs() { [native code] }
            "clone": function clone() { [native code] }
            "resolve": function resolve() { [native code] }
            "asciiSpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "asciiHostPort": "github.com"
            "asciiHost": "github.com"
            "ref": ""
            "equalsExceptRef": function equalsExceptRef() { [native code] }
            "cloneIgnoringRef": function cloneIgnoringRef() { [native code] }
            "cloneWithNewRef": function cloneWithNewRef() { [native code] }
            "specIgnoringRef": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "hasRef": false
            "filePath": "/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "query": ""
            "displayHost": "github.com"
            "displayHostPort": "github.com"
            "displaySpec": "https://github.com/daeh/zotero-obsidian-citations/releases/download/v0.0.10/zotero-obsidian-citations-0.0.10.xpi"
            "displayPrePath": "https://github.com"
            "mutate": function mutate() { [native code] }
            "QueryInterface": function QueryInterface() { [native code] }
        }
        "releaseNotesURI": null
        "name": "ZoteroObsidianCitations"
        "description": "Add a tag to Zotero items that have a external note."
        "creator": {
            "name": "Dae Houlihan"
            "url": undefined
            "toString": toString() {...}
        }
        "homepageURL": "https://github.com/daeh/zotero-obsidian-citations"
        "developers": undefined
        "translators": undefined
        "contributors": undefined
    }
]

**Comment by WMAM** [comment]
Meanwhile, I restarted my PC because of a Windows update, and... SURPRISE: everything is running right now:

BBT & ObsidianCitation plugins are running
I can open the Add-on pane
and the ObsidianCitations Preference window has changed for a new one

**Comment by daeh** [comment]
Cool. OK. that's great to know. You somehow had the addon installed twice, so you had both the v0.0.10 and v0.0.11. 

Zotero handles the autoupdates, so I'm not sure how zotero could allow that to happen, but it's really good to be aware of.

Let me know if you run into any other issues!

**Comment by WMAM** [comment]
Thank you... have a nice day!
