### ISSUE TITLE
Support finding notes linked to items in Zotero Group Libraries when Syncing Tags.

### ISSUE THREAD

**Issue by iukv** [daeh/zotero-obsidian-citations#17]

**Comment by phretor** [comment]
I second this!

**Comment by daeh** [comment]
I'll put this on the roadmap. Will hopefully be included in the next release

**Comment by daeh** [comment]
@iukv @phretor please try out the `v0.0.17a` prerelease and let me know how it works for you. 

You can turn on matching for group libraries in the advanced preferences.

You'll need to add assign a color to the ObsCite tag in each group library (in the tags plane, right click on the ObsCite tag, "Assign Color...").

https://github.com/daeh/zotero-obsidian-citations/releases/tag/v0.0.17a

**Comment by phretor** [comment]
Mh, doesn't seem to be picking up anything.

**Comment by phretor** [comment]
Nevermind, I noticed I was using lowercase citekeys. Now it find matches!
