### ISSUE TITLE
APA request

### ISSUE THREAD

**Issue by jvluyn** [daeh/zotero-obsidian-citations#21]
Hello, is there a way to create citations in APA style? The biggest issue is the way authors are shown -> 

The basic format for a book citation requires listing the author's name, the title of the book, the publisher's name, and the date of publication.

Jakupcak, M., Luterek, J., Hunt, S., Conybeare, D., & McFall, M. (2008). Post-traumatic stress and its relationship to physical health functioning in a sample of Iraq and Afghanistan war veterans seeking post-deployment VA health care. Journal of Nervous and Mental Disease, 196, 425-428.

**Comment by daeh** [comment]
This question doesn't seem related to the zotero-obsidian-citations plugin. Perhaps it's a question for the Zotero forums?
