### ISSUE TITLE
How can two devices share the same exported my library.json

### ISSUE THREAD

**Issue by EFFORTSUN** [daeh/zotero-obsidian-citations#22]
Hello, I have a question, I have zotero installed on both devices, and the data has been synced, export a my library .JSON on one device, and create the corresponding MD notes, how do I do it on the other device What about syncing notes and annotations using my library exported on the first device?

**Comment by daeh** [comment]
I'm don't understand the question. Are you sure it's one for this plugin and not [hans/obsidian-citation-plugin](https://github.com/hans/obsidian-citation-plugin)?
