### ISSUE TITLE
Error displays every time zotero starts

### ISSUE THREAD

**Issue by mgmeyers** [daeh/zotero-obsidian-citations#23]
Whenever I open zotero, I see this error from this plugin:

<img width="302" alt="Screen Shot 2022-05-16 at 3 51 38 PM" src="https://user-images.githubusercontent.com/2694747/168695015-a6acd919-ba02-49c7-bf3a-5e80590f6b89.png">

Everything seems to work ok, though. Just thought I'd report it in case there's some undefined behavior occurring.

**Comment by daeh** [comment]
hi @mgmeyers — That means that there's some mismatch between your MD files and Zotero database. That can happen if you change the BBT citekeys in Zotero and don't update the citekey in the corresponding MD file. If you manually invoke sync from the Tools menu:
`Tools` > `ZoteroObsidianCitations Sync Tags...`

you should be prompted to save an error report. The report will tell you which items cannot be matched between your MD and Zotero databases.

If you have any trouble interpreting the results, feel free to upload the file here.

Like you've noticed, hat warning won't prevent the plugin from working. It just means that the plugin cannot match some files that it thinks it should be able to match.

(If you want more detailed debugging info, you can generate a full debugging repot from `Tools` > `ZoteroObsidianCitations Preferences...` > `Advanced` > `Generate Debugging File`).

**Comment by mgmeyers** [comment]
Ah, great, thanks. Fixing those files did the trick!
