### ISSUE TITLE
Sync won't parse

### ISSUE THREAD

**Issue by cordovero** [daeh/zotero-obsidian-citations#24]
Running the sync can't match items or parse items even though yaml citekey is present and custom filter set to .+\.md$
Any help would be immensely appreciated.

I get this in the report: 

[
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "holbraad_ruptures_2019",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/holbraad_ruptures_2019.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "powers_anthropology_2019",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/powers_anthropology_2019.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "forbes_meaning_2007",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/forbes_meaning_2007.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "irvine_deep_2014",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/irvine_deep_2014.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "demossier_beyond_2011",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/demossier_beyond_2011.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "janowski_reading_2012",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/janowski_reading_2012.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "walter_uncertain_2006",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/walter_uncertain_2006.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "fabian_if_2005",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/fabian_if_2005.md"
 },
 {
  "citekey": null,
  "citekey_metadata": null,
  "citekey_title": null,
  "zotkeys": [],
  "zotids": [],
  "name": "stensrud_climate_2019",
  "path": "/Users/binou/switchdrive/Thèse/Thoughts/Research Annotations/stensrud_climate_2019.md"
 }
]

**Comment by daeh** [comment]
It looks like, for whatever reason, ZOC isn't able to read the `citekey` from the MD metadata. Can you upload the `walter_uncertain_2006.md` file?

**Comment by cordovero** [comment]
[walter_uncertain_2006.md](https://github.com/daeh/zotero-obsidian-citations/files/8788081/walter_uncertain_2006.md)

Here it is, I hope it helps!

**Comment by daeh** [comment]
It's what I expected. There's a new line before the first ```---``` of the frontmatter. MD syntax requires that metadata begin on the first line. Let me know if removing the blank new at the head of the documents don't resolve your issue.

**Comment by daeh** [comment]
(If you want more info on configuring yaml front matter: https://help.obsidian.md/Advanced+topics/YAML+front+matter )

**Comment by cordovero** [comment]
That solved it! Thank you so much. I can't believe I didn't notice the extra line...
